name: Build-and-Test-MSVC-Windows

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - dev

jobs:
  Build:
    runs-on: windows-latest
    
    strategy:
      fail-fast: false
      matrix:
        msvc: [2022]
        build_type: [Debug, Release]
        std: [20]

    steps:
    - uses: actions/checkout@v4
  
    - name: Update Vcpkg and install other dependencies.
      run: | 
            cd C:/vcpkg
            ./bootstrap-vcpkg.bat
            git stash
            git pull
            vcpkg update

    - name: Install xxHash
      run: |
            vcpkg install xxHash:x64-windows
      
    - name: Append the directory of 'vcvarsall.bat' to PATH environment variable
      uses: myci-actions/export-env-var-powershell@1
      with:
         name: PATH
         value: $env:PATH;C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build

    - name: Configure CMake
      working-directory: ./
      run: |
           cmake -S . -B ./Build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCHRISHENDO_QUALITY_TEST=true -DVCPKG_DIR=C:/vcpkg

    - name: Build the Test
      working-directory: ./Build
      run: |
           cmake --build . --config=${{matrix.build_type}}

    - name: Install the Test
      working-directory: ./Build
      run: |
           cmake --install . --config=${{matrix.build_type}}

    - name: Run the Test
      working-directory: C:/Program Files (x86)/Chrishendo/Tests/${{matrix.build_type}}/
      run: |
           ./Hash-Performance.exe
      continue-on-error: true
  